jobs:
- model_type: lm
  n_obs: 1000.0
  n_bootstraps: 1000
  heritability_source: snph2
  chunk_id: 1
  total_chunks: 1.0
- model_type: lm
  n_obs: 1000.0
  n_bootstraps: 1000
  heritability_source: twinh2
  chunk_id: 1
  total_chunks: 1.0
- model_type: lm
  n_obs: 10000.0
  n_bootstraps: 1000
  heritability_source: snph2
  chunk_id: 1
  total_chunks: 1.0
- model_type: lm
  n_obs: 10000.0
  n_bootstraps: 1000
  heritability_source: twinh2
  chunk_id: 1
  total_chunks: 1.0
- model_type: lm
  n_obs: 100000.0
  n_bootstraps: 1000
  heritability_source: snph2
  chunk_id: 1
  total_chunks: 1.0
- model_type: lm
  n_obs: 100000.0
  n_bootstraps: 1000
  heritability_source: twinh2
  chunk_id: 1
  total_chunks: 1.0
- model_type: probit
  n_obs: 1000.0
  n_bootstraps: 1000
  heritability_source: snph2
  chunk_id: 1
  total_chunks: 1.0
- model_type: probit
  n_obs: 1000.0
  n_bootstraps: 1000
  heritability_source: twinh2
  chunk_id: 1
  total_chunks: 1.0
- model_type: probit
  n_obs: 10000.0
  n_bootstraps: 1000
  heritability_source: snph2
  chunk_id: 1
  total_chunks: 1.0
- model_type: probit
  n_obs: 10000.0
  n_bootstraps: 1000
  heritability_source: twinh2
  chunk_id: 1
  total_chunks: 1.0
- model_type: probit
  n_obs: 100000.0
  n_bootstraps: 500
  heritability_source: snph2
  chunk_id: 1
  total_chunks: 2.0
- model_type: probit
  n_obs: 100000.0
  n_bootstraps: 500
  heritability_source: snph2
  chunk_id: 2
  total_chunks: 2.0
- model_type: probit
  n_obs: 100000.0
  n_bootstraps: 500
  heritability_source: twinh2
  chunk_id: 1
  total_chunks: 2.0
- model_type: probit
  n_obs: 100000.0
  n_bootstraps: 500
  heritability_source: twinh2
  chunk_id: 2
  total_chunks: 2.0
- model_type: cox
  n_obs: 1000.0
  n_bootstraps: 1000
  heritability_source: snph2
  chunk_id: 1
  total_chunks: 1.0
- model_type: cox
  n_obs: 1000.0
  n_bootstraps: 1000
  heritability_source: twinh2
  chunk_id: 1
  total_chunks: 1.0
- model_type: cox
  n_obs: 10000.0
  n_bootstraps: 1000
  heritability_source: snph2
  chunk_id: 1
  total_chunks: 1.0
- model_type: cox
  n_obs: 10000.0
  n_bootstraps: 1000
  heritability_source: twinh2
  chunk_id: 1
  total_chunks: 1.0
- model_type: cox
  n_obs: 100000.0
  n_bootstraps: 200
  heritability_source: snph2
  chunk_id: 1
  total_chunks: 5.0
- model_type: cox
  n_obs: 100000.0
  n_bootstraps: 200
  heritability_source: snph2
  chunk_id: 2
  total_chunks: 5.0
- model_type: cox
  n_obs: 100000.0
  n_bootstraps: 200
  heritability_source: snph2
  chunk_id: 3
  total_chunks: 5.0
- model_type: cox
  n_obs: 100000.0
  n_bootstraps: 200
  heritability_source: snph2
  chunk_id: 4
  total_chunks: 5.0
- model_type: cox
  n_obs: 100000.0
  n_bootstraps: 200
  heritability_source: snph2
  chunk_id: 5
  total_chunks: 5.0
- model_type: cox
  n_obs: 100000.0
  n_bootstraps: 200
  heritability_source: twinh2
  chunk_id: 1
  total_chunks: 5.0
- model_type: cox
  n_obs: 100000.0
  n_bootstraps: 200
  heritability_source: twinh2
  chunk_id: 2
  total_chunks: 5.0
- model_type: cox
  n_obs: 100000.0
  n_bootstraps: 200
  heritability_source: twinh2
  chunk_id: 3
  total_chunks: 5.0
- model_type: cox
  n_obs: 100000.0
  n_bootstraps: 200
  heritability_source: twinh2
  chunk_id: 4
  total_chunks: 5.0
- model_type: cox
  n_obs: 100000.0
  n_bootstraps: 200
  heritability_source: twinh2
  chunk_id: 5
  total_chunks: 5.0
